version: "3.9"
services:
  base:
    image: tampl:base
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    # Interactive shell
    stdin_open: true
    tty: true
    # Needed to display graphical applications
    network_mode: host
    privileged: true
  dev:
    image: tampl:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    volumes:
      # Mount source code
      - .:/workspace:rw
    command: sleep infinity
  novnc:
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=2560
      - DISPLAY_HEIGHT=1440
    ports:
      - "8080:8080"
    networks:
      - x11
    restart: on-failure
networks:
  x11: