
environment:
  id: "example_cpp"

# environments:
#   # List of unique environment names
#   - "tower_of_hanoi"
#   - "mujoco"

## python based environments

tower_of_hanoi:
  type: python
  module: pytampl.extensions.pddlgym
  class: PDDLGymEnv
  # env specific params
  params:
    env_name: PDDLEnvHanoi-v0

## c++ based environments

example_cpp:
  type: "cpp"

# TODO: add c++ examples
mujoco:
  type: cpp
  # env specific params
  params:
    env_name: PDDLEnvHanoi-v0