#pragma once

#include "behaviortree_cpp/behavior_tree.h"
#include "behaviortree_cpp/bt_factory.h"
#include "behaviortree_cpp/utils/shared_library.h"
#include "gen/plugins_list.hpp"
#include "tampl/core/action.hpp"

namespace tampl::bt {

/**
 * @class PlannerBTEngine
 * @brief This class is responsible for running a behavior tree planner engine.
 *
 * The `PlannerBTEngine` class loads and runs a behavior tree (BT) defined in an
 * XML file and provides an interface to retrieve the generated plan as a
 * sequence of TAMPL's actions.
 */
class PlannerBTEngine {
public:
  /**
   * @brief Constructs a PlannerBTEngine with a specified behavior tree.
   *
   * @param bt_xml_path Path to the XML file defining the behavior tree.
   */
  PlannerBTEngine(const std::string &bt_xml_path,
                  const std::string &domain_file,
                  const std::string &problem_file);

  /**
   * @brief Destructor for the PlannerBTEngine class.
   */
  ~PlannerBTEngine();

  /**
   * @brief Runs the behavior tree and generates a plan.
   * @return True if the behavior tree was successfully executed, false
   * otherwise.
   */
  bool run();

  /**
   * @brief Gets the generated plan as a vector of actions.
   * @return A constant reference to the plan.
   */
  const std::vector<core::Action> &get_plan() const;

private:
  /// @brief Factory to create the behavior tree.
  BT::BehaviorTreeFactory bt_factory_;

  /// @brief Behavior tree instance.
  BT::Tree tree_;

  BT::Blackboard::Ptr bb_;

  /// @brief Plan generated by the behavior tree.
  std::vector<core::Action> plan_;
};

} // namespace tampl::bt